-- Fjord & Cotton — migration: Gelato-hosted mockups
-- Run after 02c-catalog-facets.sql.
--
-- Mockups are generated by Gelato from a product template instead of being
-- composited locally. Gelato returns one image per variant, so a single
-- designs.mockup_url is no longer enough — we need one URL per garment colour.

-- Link a design to the Gelato product it created.
alter table designs add column if not exists gelato_product_id text;
alter table designs add column if not exists gelato_template_id text;

-- Mockups arrive asynchronously: Gelato publishes them in the background after
-- the product is created. The storefront needs to know when they are ready.
do $$ begin
  create type mockup_state as enum ('pending', 'ready', 'failed');
exception when duplicate_object then null; end $$;

alter table designs add column if not exists mockup_status mockup_state not null default 'pending';

-- One mockup per design × colour. Sizes share an image — a print does not look
-- different on an L than on an M.
create table if not exists design_mockups (
  id         uuid primary key default gen_random_uuid(),
  design_id  uuid not null references designs(id) on delete cascade,
  color_id   uuid not null references garment_colors(id) on delete cascade,
  url        text not null,
  is_primary boolean not null default false,   -- the one used on catalog tiles
  sort_order int  not null default 0,
  unique (design_id, color_id)
);

create index if not exists design_mockups_design_idx on design_mockups(design_id);

-- Exactly one primary per design.
create unique index if not exists design_mockups_one_primary
  on design_mockups(design_id) where is_primary;

-- designs.mockup_url stays as a denormalised pointer to the primary mockup so
-- catalog queries do not need a join. Keep it in sync.
create or replace function sync_primary_mockup()
returns trigger language plpgsql as $$
begin
  if new.is_primary then
    update designs set mockup_url = new.url where id = new.design_id;
  end if;
  return new;
end $$;

drop trigger if exists design_mockups_sync on design_mockups;
create trigger design_mockups_sync
  after insert or update on design_mockups
  for each row execute function sync_primary_mockup();

-- Only surface designs whose mockups have actually landed. A tile with a broken
-- image is worse than a tile that is not there yet.
create or replace view catalog_designs as
  select d.* from designs d
  where d.status = 'published' and d.mockup_status = 'ready';

grant select on catalog_designs to anon, authenticated;
grant select on design_mockups to anon, authenticated;
